version: "2.0"
services:
  nginx-web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/akilan/Desktop/nginx-ssl/certs:/etc/nginx/certs
      - /home/akilan/Desktop/nginx-ssl/nginx.conf:/etc/nginx/nginx.conf
